version: "3"

services:
  backend:
    build: ./back
    command: python3.9 /back/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/back
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
  frontend:
    build: ./front
    volumes:
      - ./front:/front
    ports:
      - '3000:3000'
    stdin_open: true
    depends_on:
      - "backend"
    command:
      npm start
