# Generated by Django 3.1.4 on 2020-12-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('C', 'Children')], default=None, max_length=1),
        ),
    ]
