# Generated by Django 3.1.4 on 2020-12-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201226_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('0', 'Man'), ('1', 'Woman'), ('2', 'Children')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
