# Generated by Django 3.1.4 on 2021-02-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
